# Generated by Django 5.0.7 on 2026-08-24 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, unique=True)),
                (
                    "device_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "op_type",
                    models.CharField(
                        choices=[
                            ("create", "Crear"),
                            ("update", "Actualizar"),
                            ("delete", "Eliminar"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="task, project, comment, etc.", max_length=50
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(help_text="Client-side UUID", max_length=100),
                ),
                ("server_entity_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "payload",
                    models.JSONField(default=dict, help_text="Datos de la entidad"),
                ),
                ("client_timestamp", models.DateTimeField()),
                ("server_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("applied", "Aplicada"),
                            ("conflict", "Conflicto"),
                            ("rejected", "Rechazada"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "conflict_data",
                    models.JSONField(
                        blank=True,
                        help_text="Datos del servidor en conflicto",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="offline_sync.syncdevice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="sync_op_user_status_idx"
                    ),
                    models.Index(
                        fields=["device", "status"], name="sync_op_dev_status_idx"
                    ),
                ],
            },
        ),
    ]
