# Generated by Django 5.0.7 on 2026-08-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offline_sync", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncdevice",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Si el dispositivo está activo/revocado"
            ),
        ),
        migrations.AddField(
            model_name="syncoperation",
            name="base_version",
            field=models.IntegerField(
                blank=True,
                help_text="Versión del recurso que el cliente tenía al hacer el cambio",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="syncoperation",
            name="conflict_status",
            field=models.CharField(
                choices=[
                    ("none", "Sin conflicto"),
                    ("conflict", "Conflicto"),
                    ("resolved", "Resuelto"),
                ],
                default="none",
                help_text="Estado de detección de conflictos por versión",
                max_length=10,
            ),
        ),
    ]
