# Generated by Django 5.2.17 on 2026-09-24 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0004_organization_organizationmembership'),
        ('projects', '0003_projectrisk'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tenant opcional: los miembros de la org heredan acceso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='collaboration.organization'),
        ),
    ]
