# Generated by Django 5.2.17 on 2026-09-26 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_portfolio_projecttemplate_projectstatelabel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="health",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on_track", "En camino"),
                    ("at_risk", "En riesgo"),
                    ("off_track", "Desviado"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ProjectStatusUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "health",
                    models.CharField(
                        choices=[
                            ("on_track", "En camino"),
                            ("at_risk", "En riesgo"),
                            ("off_track", "Desviado"),
                        ],
                        default="on_track",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="", max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_status_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updates",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
