# Generated by Django 5.2.17 on 2026-09-26 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_project_health_projectstatusupdate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectstatusupdate",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
