# Generated by Django 5.2.17 on 2026-09-26 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_projectstatusupdate_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="issue_prefix",
            field=models.CharField(blank=True, default="", max_length=6),
        ),
        migrations.CreateModel(
            name="ProjectSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("project", "name")},
            },
        ),
    ]
