# Generated by Django 5.2.17 on 2026-09-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_project_favorited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttemplate",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projecttemplate",
            name="use_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
