[mypy]
plugins = mypy_django_plugin.main
ignore_missing_imports = True
exclude = migrations|\.lintenv|\.venv|tests|mutants|backend_mutdbg

[mypy.plugins.django-stubs]
django_settings_module = config.settings_test

[mypy-*.migrations.*]
ignore_errors = True
