# Generated by Django 5.2.17 on 2026-09-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_pushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="digest_frequency",
            field=models.CharField(
                choices=[("daily", "Diario"), ("weekly", "Semanal")],
                default="daily",
                max_length=10,
            ),
        ),
    ]
