# Generated by Django 5.0.7 on 2026-08-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aisuggestion",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("accepted", "Aceptada"),
                    ("rejected", "Rechazada"),
                    ("applied", "Aplicada"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
