# Generated by Django 5.0.7 on 2026-08-24 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "encrypted_data",
                    models.TextField(
                        help_text="Datos cifrados en base64 (título, descripción, etc.)"
                    ),
                ),
                (
                    "encryption_key_id",
                    models.CharField(
                        help_text="ID de la clave usada para cifrar", max_length=100
                    ),
                ),
                (
                    "iv",
                    models.CharField(
                        help_text="Vector de inicialización en base64", max_length=64
                    ),
                ),
                (
                    "auth_tag",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tag de autenticación (GCM)",
                        max_length=64,
                    ),
                ),
                ("algorithm", models.CharField(default="AES-256-GCM", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encrypted_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPublicKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key", models.TextField(help_text="Clave pública en base64")),
                (
                    "key_id",
                    models.CharField(help_text="ID único de la clave", max_length=100),
                ),
                (
                    "algorithm",
                    models.CharField(
                        default="RSA-OA-256",
                        help_text="Algoritmo: RSA-OA-256, X25519",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "key_id")},
            },
        ),
        migrations.CreateModel(
            name="EncryptedKeyShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "encrypted_key",
                    models.TextField(
                        help_text="Clave AES cifrada con la clave pública del usuario"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encrypted_key_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encrypted_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_shares",
                        to="encryption.encryptedtask",
                    ),
                ),
                (
                    "user_public_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="encryption.userpublickey",
                    ),
                ),
            ],
            options={
                "unique_together": {("encrypted_task", "user")},
            },
        ),
    ]
