# Generated by Django 5.0.7 on 2026-08-29 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encryption", "0001_initial"),
        ("tasks", "0007_task_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptedtask",
            name="task",
            field=models.OneToOneField(
                blank=True,
                help_text="Tarea relacionada (FK real para integridad referencial)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encrypted_data",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="userpublickey",
            name="rotated_at",
            field=models.DateTimeField(
                blank=True, help_text="Fecha de rotación de la clave", null=True
            ),
        ),
    ]
