# Generated by Django 5.2.17 on 2026-09-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_hash_legacy_backup_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ical_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
