# Generated by Django 5.2.17 on 2026-09-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_email_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="inbound_email_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
