# Generated by Django 5.2.17 on 2026-09-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_inbound_email_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="weekly_capacity_hours",
            field=models.DecimalField(decimal_places=1, default=40, max_digits=5),
        ),
    ]
