# Generated by Django 5.2.17 on 2026-09-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_weekly_capacity_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="out_of_office",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="out_of_office_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
