# Generated by Django 5.2.17 on 2026-09-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_out_of_office_user_out_of_office_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="scim_external_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="scim_id",
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="scim_username",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
    ]
