# Generated by Django 5.0.7 on 2026-08-24 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("task_created", "Tarea creada"),
                            ("task_state_changed", "Estado cambiado"),
                            ("task_completed", "Tarea completada"),
                            ("task_blocked", "Tarea bloqueada"),
                            ("task_overdue", "Tarea vencida"),
                            ("comment_added", "Comentario añadido"),
                            ("sprint_started", "Sprint iniciado"),
                            ("sprint_closed", "Sprint cerrado"),
                            ("daily_check", "Chequeo diario"),
                        ],
                        max_length=30,
                    ),
                ),
                ("conditions", models.JSONField(blank=True, default=list)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("set_priority", "Cambiar prioridad"),
                            ("set_state", "Cambiar estado"),
                            ("set_assignee", "Asignar responsable"),
                            ("add_tag", "Añadir etiqueta"),
                            ("set_due_date", "Establecer fecha límite"),
                            ("move_to_sprint", "Mover a sprint"),
                            ("subtasks_in_progress", "Subtareas a in_progress"),
                            ("create_notification", "Crear notificación"),
                            ("create_task", "Crear tarea"),
                        ],
                        max_length=30,
                    ),
                ),
                ("action_params", models.JSONField(blank=True, default=dict)),
                ("trigger_count", models.PositiveIntegerField(default=0)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Éxito"),
                            ("failed", "Fallido"),
                            ("skipped", "Omitido"),
                        ],
                        max_length=20,
                    ),
                ),
                ("trigger_data", models.JSONField(blank=True, default=dict)),
                ("action_result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="automations.automationrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
