# Generated by Django 5.0.7 on 2026-09-23 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.PositiveSmallIntegerField(help_text='Prioridad de las tareas a las que aplica (P0-P5)')),
                ('response_hours', models.PositiveIntegerField(default=24, help_text='Horas máximas hasta que la tarea se empieza (in_progress)')),
                ('resolution_hours', models.PositiveIntegerField(default=72, help_text='Horas máximas hasta que la tarea se completa')),
                ('bump_priority', models.BooleanField(default=True, help_text='Escalar prioridad un nivel al incumplir el SLA')),
                ('notify_owner', models.BooleanField(default=True)),
                ('notify_assignee', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority'],
                'unique_together': {('owner', 'priority')},
            },
        ),
    ]
