# Generated by Django 5.0.7 on 2026-09-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_slapolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='schedule_hours',
            field=models.PositiveIntegerField(default=24, help_text='Intervalo en horas para reglas SCHEDULED (p.ej. 8, 24, 168)'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger',
            field=models.CharField(choices=[('task_created', 'Tarea creada'), ('task_state_changed', 'Estado cambiado'), ('task_completed', 'Tarea completada'), ('task_blocked', 'Tarea bloqueada'), ('task_overdue', 'Tarea vencida'), ('comment_added', 'Comentario añadido'), ('sprint_started', 'Sprint iniciado'), ('sprint_closed', 'Sprint cerrado'), ('daily_check', 'Chequeo diario'), ('scheduled', 'Programada (cada N horas)')], max_length=30),
        ),
    ]
