# Generated by Django 5.2.17 on 2026-09-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automations", "0003_automationrule_schedule_hours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationrule",
            name="action",
            field=models.CharField(
                choices=[
                    ("set_priority", "Cambiar prioridad"),
                    ("set_state", "Cambiar estado"),
                    ("set_assignee", "Asignar responsable"),
                    ("add_tag", "Añadir etiqueta"),
                    ("set_due_date", "Establecer fecha límite"),
                    ("move_to_sprint", "Mover a sprint"),
                    ("subtasks_in_progress", "Subtareas a in_progress"),
                    ("create_notification", "Crear notificación"),
                    ("create_task", "Crear tarea"),
                    ("create_subtask", "Crear subtarea (checklist)"),
                    ("set_due_offset", "Fecha límite en N días"),
                    ("post_comment", "Publicar comentario"),
                    ("move_to_project", "Mover a proyecto"),
                ],
                max_length=30,
            ),
        ),
    ]
