# Generated by Django 5.2.17 on 2026-09-24 08:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processed', 'Procesado'), ('failed', 'Fallido')], db_index=True, default='pending', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='events_outb_status_1831f4_idx')],
            },
        ),
    ]
