# Generated by Django 5.2.17 on 2026-09-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okrs", "0001_initial"),
        ("tasks", "0013_attachment_external_url_alter_attachment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyresult",
            name="linked_tasks",
            field=models.ManyToManyField(
                blank=True, related_name="linked_key_results", to="tasks.task"
            ),
        ),
    ]
