# Generated by Django 5.2.17 on 2026-10-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okrs", "0002_keyresult_linked_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyresult",
            name="direction",
            field=models.CharField(
                choices=[
                    ("increase", "Higher is better"),
                    ("decrease", "Lower is better"),
                ],
                default="increase",
                max_length=10,
            ),
        ),
    ]
