# Generated by Django 5.0.7 on 2026-08-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
