# Generated by Django 5.2.17 on 2026-09-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0005_externalcalendar_whiteboard_externalevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="video_room",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
    ]
