# Generated by Django 5.2.17 on 2026-09-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0006_meeting_video_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="scim_display_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="scim_external_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="scim_id",
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="sso_domain",
            field=models.CharField(
                blank=True, db_index=True, max_length=253, null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="sso_required",
            field=models.BooleanField(default=False),
        ),
    ]
