# Generated by Django 5.0.7 on 2026-08-24 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurrenceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Diaria"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                            ("yearly", "Anual"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("interval", models.PositiveIntegerField(default=1)),
                ("until", models.DateTimeField(blank=True, null=True)),
                ("count", models.PositiveIntegerField(blank=True, null=True)),
                ("occurrences_generated", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (0, "P0 Critica"),
                    (1, "P1 Muy alta"),
                    (2, "P2 Alta"),
                    (3, "P3 Media"),
                    (4, "P4 Baja"),
                    (5, "P5 Algun dia"),
                ],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="state",
            field=models.CharField(
                choices=[
                    ("backlog", "Backlog"),
                    ("pending", "Pendiente"),
                    ("in_progress", "En progreso"),
                    ("blocked", "Bloqueada"),
                    ("review", "En revision"),
                    ("completed", "Completada"),
                    ("cancelled", "Cancelada"),
                    ("archived", "Archivada"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.recurrencerule",
            ),
        ),
    ]
