# Generated by Django 5.0.7 on 2026-08-24 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
        ("tags", "0002_initial"),
        ("tasks", "0003_recurrencerule_alter_task_priority_alter_task_state_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Creada"),
                            ("updated", "Actualizada"),
                            ("state_changed", "Cambio de estado"),
                            ("priority_changed", "Cambio de prioridad"),
                            ("assigned", "Asignada"),
                            ("label_added", "Etiqueta anadida"),
                            ("label_removed", "Etiqueta retirada"),
                            ("sprint_changed", "Cambio de sprint"),
                            ("commented", "Comentada"),
                            ("closed", "Cerrada"),
                            ("reopened", "Reabierta"),
                            ("subtask_added", "Subtarea anadida"),
                            ("relation_added", "Relacion anadida"),
                        ],
                        max_length=30,
                    ),
                ),
                ("field", models.CharField(blank=True, default="", max_length=50)),
                ("old_value", models.TextField(blank=True, default="")),
                ("new_value", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("blocks", "Bloquea"),
                            ("related", "Relacionada con"),
                            ("duplicates", "Duplica"),
                            ("replaces", "Sustituye"),
                            ("depends_on", "Depende de"),
                            ("requirement", "Es requisito de"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="estimate_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks_children",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("xs", "XS"),
                    ("s", "S"),
                    ("m", "M"),
                    ("l", "L"),
                    ("xl", "XL"),
                ],
                default="",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="story_points",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("bug", "Bug"),
                    ("feature", "Funcionalidad"),
                    ("improvement", "Mejora"),
                    ("task", "Tarea"),
                    ("research", "Investigacion"),
                    ("tech_debt", "Deuda tecnica"),
                    ("docs", "Documentacion"),
                    ("ops", "Incidencia operativa"),
                ],
                default="task",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Epic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("planned", "Planificada"),
                            ("in_progress", "En progreso"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="planned",
                        max_length=15,
                    ),
                ),
                ("color", models.CharField(default="#9c27b0", max_length=7)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epics",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="epic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.epic",
            ),
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("filters", models.JSONField(default=dict)),
                ("is_shared", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("goal", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("planned", "Planificado"),
                            ("active", "Activo"),
                            ("closed", "Cerrado"),
                        ],
                        default="planned",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.sprint",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["task_type"], name="tasks_task_task_ty_45f0a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["sprint"], name="tasks_task_sprint__694521_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["epic"], name="tasks_task_epic_id_10ab85_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["parent"], name="tasks_task_parent__383e16_idx"),
        ),
        migrations.AddField(
            model_name="taskactivity",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskactivity",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="taskrelation",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_relations",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="taskrelation",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_relations",
                to="tasks.task",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedsearch",
            unique_together={("name", "owner")},
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(fields=["state"], name="tasks_sprin_state_d02264_idx"),
        ),
        migrations.AddIndex(
            model_name="taskactivity",
            index=models.Index(
                fields=["task", "created_at"], name="tasks_taska_task_id_88cdfc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskrelation",
            unique_together={("source", "target", "relation_type")},
        ),
    ]
