# Generated by Django 5.0.7 on 2026-08-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_recurrencerule_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="version",
            field=models.IntegerField(
                default=1, help_text="Versión del recurso, se incrementa en cada save"
            ),
        ),
    ]
