# Generated by Django 5.0.7 on 2026-09-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_task_owner_state_idx_task_task_proj_state_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tasks.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
