# Generated by Django 5.2.17 on 2026-09-25 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_comment_parent_comment_reactions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Usuarios asignados adicionales a la tarea",
                related_name="assigned_tasks_multi",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reminder_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="watchers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Usuarios que observan la tarea",
                related_name="watched_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="is_running",
            field=models.BooleanField(default=False),
        ),
    ]
