# Generated by Django 5.2.17 on 2026-09-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_task_assignees_task_reminder_at_task_reminder_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="external_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(blank=True, upload_to="attachments/"),
        ),
    ]
