# Generated by Django 5.2.17 on 2026-09-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0014_taskapproval"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
