# Generated by Django 5.2.17 on 2026-09-26 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_project_issue_prefix_projectsection"),
        ("tasks", "0015_task_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="projects.projectsection",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="seq",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
