# Generated by Django 5.2.17 on 2026-09-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0018_backfill_task_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-is_pinned", "-created_at"]},
        ),
        migrations.AddField(
            model_name="task",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
