# Generated by Django 5.2.17 on 2026-09-27 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0019_alter_task_options_task_is_pinned"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Usuarios que marcaron la tarea como favorita",
                related_name="favorite_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="is_milestone",
            field=models.BooleanField(default=False),
        ),
    ]
