# Generated by Django 5.2.17 on 2026-09-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0020_task_favorited_by_task_is_milestone"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="caldav_uid",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
    ]
