# Generated by Django 5.2.17 on 2026-09-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_project_favorited_by"),
        ("tasks", "0021_task_caldav_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="extra_projects",
            field=models.ManyToManyField(
                blank=True, related_name="homed_tasks", to="projects.project"
            ),
        ),
    ]
