# Generated by Django 5.0.7 on 2026-08-24 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0003_recurrencerule_alter_task_priority_alter_task_state_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installation_id", models.BigIntegerField(unique=True)),
                ("account_login", models.CharField(max_length=255)),
                ("account_type", models.CharField(default="User", max_length=50)),
                ("avatar_url", models.URLField(blank=True, default="", max_length=500)),
                ("github_user_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "github_username",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("access_token", models.TextField(blank=True, default="")),
                ("refresh_token", models.TextField(blank=True, default="")),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_installations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GitHubRepo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_id", models.BigIntegerField()),
                ("full_name", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("owner", models.CharField(max_length=255)),
                ("is_private", models.BooleanField(default=False)),
                ("sync_enabled", models.BooleanField(default=True)),
                ("default_branch", models.CharField(default="main", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repos",
                        to="integrations.githubinstallation",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
                "unique_together": {("installation", "repo_id")},
            },
        ),
        migrations.CreateModel(
            name="GitHubIssueLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_number", models.IntegerField()),
                ("issue_id", models.BigIntegerField()),
                ("issue_url", models.URLField(max_length=500)),
                ("issue_state", models.CharField(default="open", max_length=20)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project_node_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "project_status",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_link",
                        to="tasks.task",
                    ),
                ),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_links",
                        to="integrations.githubrepo",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("repo", "issue_number")},
            },
        ),
    ]
