# Generated by Django 5.0.7 on 2026-08-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("action", models.CharField(blank=True, default="", max_length=50)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processed", "Procesado"),
                            ("failed", "Fallido"),
                            ("retrying", "Reintentando"),
                            ("dead_letter", "Cola de mensajes fallidos"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=5)),
                (
                    "repo_full_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="integration_status_d14ae6_idx"
                    ),
                    models.Index(
                        fields=["next_retry_at"], name="integration_next_re_a21833_idx"
                    ),
                ],
            },
        ),
    ]
