# Generated by Django 5.0.7 on 2026-08-24 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_webhookdelivery"),
        ("tasks", "0004_taskactivity_taskrelation_task_estimate_hours_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubCommit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sha", models.CharField(max_length=40, unique=True)),
                ("message", models.TextField()),
                ("author", models.CharField(blank=True, default="", max_length=255)),
                ("author_date", models.DateTimeField(blank=True, null=True)),
                ("html_url", models.URLField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="integrations.githubrepo",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        blank=True, related_name="commits", to="tasks.task"
                    ),
                ),
            ],
            options={
                "ordering": ["-author_date"],
            },
        ),
        migrations.CreateModel(
            name="GitHubPullRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pr_number", models.IntegerField()),
                ("pr_id", models.BigIntegerField()),
                ("title", models.CharField(max_length=500)),
                ("state", models.CharField(default="open", max_length=20)),
                ("is_merged", models.BooleanField(default=False)),
                ("is_draft", models.BooleanField(default=False)),
                ("html_url", models.URLField(max_length=500)),
                (
                    "head_branch",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "base_branch",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("author", models.CharField(blank=True, default="", max_length=255)),
                ("created_at_gh", models.DateTimeField(blank=True, null=True)),
                ("merged_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("review_comments_count", models.IntegerField(default=0)),
                ("approvals_count", models.IntegerField(default=0)),
                ("changes_requested", models.BooleanField(default=False)),
                ("ci_status", models.CharField(blank=True, default="", max_length=50)),
                ("ci_url", models.URLField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_requests",
                        to="integrations.githubrepo",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        blank=True, related_name="pull_requests", to="tasks.task"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at_gh"],
                "unique_together": {("repo", "pr_number")},
            },
        ),
        migrations.CreateModel(
            name="GitHubCheckRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "En cola"),
                            ("in_progress", "En progreso"),
                            ("completed", "Completado"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "conclusion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Éxito"),
                            ("failure", "Fallo"),
                            ("neutral", "Neutral"),
                            ("cancelled", "Cancelado"),
                            ("skipped", "Omitido"),
                            ("timed_out", "Tiempo agotado"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("html_url", models.URLField(blank=True, default="", max_length=500)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("commit_sha", models.CharField(blank=True, default="", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_runs",
                        to="integrations.githubrepo",
                    ),
                ),
                (
                    "pull_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="check_runs",
                        to="integrations.githubpullrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="GitHubRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("release_id", models.BigIntegerField(unique=True)),
                ("tag_name", models.CharField(max_length=255)),
                ("name", models.CharField(blank=True, default="", max_length=500)),
                ("body", models.TextField(blank=True, default="")),
                ("html_url", models.URLField(max_length=500)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicada"),
                            ("prerelease", "Pre-release"),
                        ],
                        default="published",
                        max_length=20,
                    ),
                ),
                ("is_prerelease", models.BooleanField(default=False)),
                ("author", models.CharField(blank=True, default="", max_length=255)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pull_requests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="releases",
                        to="integrations.githubpullrequest",
                    ),
                ),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="integrations.githubrepo",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        blank=True, related_name="releases", to="tasks.task"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
