# Generated by Django 5.0.7 on 2026-09-22 17:42

from django.db import migrations

import apps.integrations.fields


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_githubcommit_githubpullrequest_githubcheckrun_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubinstallation",
            name="access_token",
            field=apps.integrations.fields.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="githubinstallation",
            name="refresh_token",
            field=apps.integrations.fields.EncryptedTextField(blank=True, default=""),
        ),
    ]
