# Generated by Django 5.2.17 on 2026-09-25 22:57

import secrets

from django.db import migrations, models


def backfill_public_tokens(apps, schema_editor):
    """Genera un public_token único para los formularios existentes."""
    IntakeForm = apps.get_model("intake", "IntakeForm")
    for form in IntakeForm.objects.filter(public_token__isnull=True):
        form.public_token = secrets.token_urlsafe(32)
        form.save(update_fields=["public_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="intakeform",
            name="public_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.RunPython(
            backfill_public_tokens, reverse_code=migrations.RunPython.noop
        ),
    ]
